---
- hosts: all
  vars:
  - aaa2: "{{aaa|default('AA')}}"
  - bbb2: "{{bbb|default('BB')}}"
  - ccc2: "{{ccc|default('CC')}}"
  tasks:
  - name: PrintSomething
    debug: var=aaa2
  - name: PrintSomething
    debug: var=bbb2
  - name: PrintSomething
    debug: var=ccc2
